GET http://localhost:3001/
Content-Type: application/json

{
  "message": "FUC YOU TOO"
}

GET http://localhost:3001/

POST http://localhost:3001/
Content-Type: application/json

{
  "id": 1,
  "name": "frappuccino",
  "description": "pretty much a milkshake with coffee"
}

PUT http://localhost:3001/1
Content-Type: application/json

{
  "id": 1,
  "name": "tea",
  "description": "a nice cup of tea"
}
